language: ruby
rvm:
  - 2.4

install:
  - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
  - sudo apt-get install -y nodejs node
  - node --version
  - nodejs --version
  - yarn install
  - bundle install

script:
  - yarn run stylelint && bundle exec jekyll build
