language: ruby
rvm:
  - 2.4

install:
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.2/install.sh | bash
  - nvm install node
  - yarn install
  - bundle install

script:
  - yarn run stylelint
  - ./build.sh

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_API_KEY
  target-branch: gh-pages
  local_dir: _site
  verbose: true
  on:
    branch: master

cache:
  bundler: true
  yarn: true
